# Generated by Django 5.1 on 2024-08-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohjelma', '0002_alter_työntekijä_työsuhteen_tyyppi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='työntekijä',
            name='osoite',
        ),
        migrations.AddField(
            model_name='työntekijä',
            name='katuosoite',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='työntekijä',
            name='postinumero',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='työntekijä',
            name='postitoimipaikka',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='työntekijä',
            name='lopetus_pvm',
            field=models.DateField(blank=True, null=True),
        ),
    ]
