# Generated by Django 5.1 on 2024-09-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohjelma', '0003_alter_maakunta_nimi'),
    ]

    operations = [
        migrations.AddField(
            model_name='työntekijä',
            name='työnkuva',
            field=models.CharField(default='oo', max_length=100),
            preserve_default=False,
        ),
    ]
