# Generated by Django 5.1 on 2024-09-10 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ohjelma', '0004_työntekijä_työnkuva'),
    ]

    operations = [
        migrations.RenameField(
            model_name='työntekijä',
            old_name='työnkuva',
            new_name='työtehtävä',
        ),
    ]
