# Generated by Django 5.1 on 2024-08-23 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohjelma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='työntekijä',
            name='työsuhteen_tyyppi',
            field=models.CharField(choices=[('vakituinen', 'Vakituinen'), ('määräaikainen', 'Määräaikainen')], default='vakituinen', max_length=50),
        ),
    ]
