# Generated by Django 5.1 on 2024-09-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohjelma', '0004_kunta_alter_työntekijä_options_työpiste_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kunta',
            name='maakunta',
            field=models.CharField(choices=[('ahvenanmaa', 'Ahvenanmaa'), ('etela_karjala', 'Etelä-Karjala'), ('etela_pohjanmaa', 'Etelä-Pohjanmaa'), ('etela_savo', 'Etelä-Savo'), ('kainuu', 'Kainuu'), ('kanta_hame', 'Kanta-Häme'), ('keski_pohjanmaa', 'Keski-Pohjanmaa'), ('keski_suomi', 'Keski-Suomi'), ('kymenlaakso', 'Kymenlaakso'), ('lappi', 'Lappi'), ('pirkanmaa', 'Pirkanmaa'), ('pohjanmaa', 'Pohjanmaa'), ('pohjois_karjala', 'Pohjois-Karjala'), ('pohjois_pohjanmaa', 'Pohjois-Pohjanmaa'), ('pohjois_savo', 'Pohjois-Savo'), ('paijat_hame', 'Päijät-Häme'), ('satakunta', 'Satakunta'), ('uusimaa', 'Uusimaa'), ('varsinais_suomi', 'Varsinais-Suomi')], max_length=20),
        ),
    ]
