# Generated by Django 5.1 on 2024-09-03 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ohjelma', '0008_remove_työpiste_kunta_remove_työntekijä_työkunta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'kunnat',
            },
        ),
        migrations.CreateModel(
            name='Maakunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(choices=[('ahvenanmaa', 'Ahvenanmaa'), ('etela_karjala', 'Etelä-Karjala'), ('etela_pohjanmaa', 'Etelä-Pohjanmaa'), ('etela_savo', 'Etelä-Savo'), ('kainuu', 'Kainuu'), ('kanta_hame', 'Kanta-Häme'), ('keski_pohjanmaa', 'Keski-Pohjanmaa'), ('keski_suomi', 'Keski-Suomi'), ('kymenlaakso', 'Kymenlaakso'), ('lappi', 'Lappi'), ('pirkanmaa', 'Pirkanmaa'), ('pohjanmaa', 'Pohjanmaa'), ('pohjois_karjala', 'Pohjois-Karjala'), ('pohjois_pohjanmaa', 'Pohjois-Pohjanmaa'), ('pohjois_savo', 'Pohjois-Savo'), ('paijat_hame', 'Päijät-Häme'), ('satakunta', 'Satakunta'), ('uusimaa', 'Uusimaa'), ('varsinais_suomi', 'Varsinais-Suomi')], default='uusimaa', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'maakunnat',
            },
        ),
        migrations.AddField(
            model_name='työntekijä',
            name='työkunta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ohjelma.kunta'),
        ),
        migrations.AddField(
            model_name='kunta',
            name='maakunta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ohjelma.maakunta'),
        ),
        migrations.AddField(
            model_name='työntekijä',
            name='työmaakunta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ohjelma.maakunta'),
        ),
        migrations.CreateModel(
            name='Työpiste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(max_length=50)),
                ('katuosoite', models.CharField(max_length=100)),
                ('postinumero', models.CharField(max_length=10)),
                ('postitoimipaikka', models.CharField(max_length=50)),
                ('kunta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ohjelma.kunta')),
            ],
            options={
                'verbose_name_plural': 'työpisteet',
            },
        ),
        migrations.AddField(
            model_name='työntekijä',
            name='työpiste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ohjelma.työpiste'),
        ),
    ]
