# Generated by Django 5.1 on 2024-09-03 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ohjelma', '0009_kunta_maakunta_työntekijä_työkunta_kunta_maakunta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='työpiste',
            name='kunta',
        ),
        migrations.RemoveField(
            model_name='työntekijä',
            name='työkunta',
        ),
        migrations.RemoveField(
            model_name='työntekijä',
            name='työmaakunta',
        ),
        migrations.RemoveField(
            model_name='työntekijä',
            name='työpiste',
        ),
        migrations.DeleteModel(
            name='Kunta',
        ),
        migrations.DeleteModel(
            name='Maakunta',
        ),
        migrations.DeleteModel(
            name='Työntekijä',
        ),
        migrations.DeleteModel(
            name='Työpiste',
        ),
    ]
