# Generated by Django 5.1 on 2024-09-03 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ohjelma', '0010_remove_työpiste_kunta_remove_työntekijä_työkunta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maakunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(choices=[('ahvenanmaa', 'Ahvenanmaa'), ('etela_karjala', 'Etelä-Karjala'), ('etela_pohjanmaa', 'Etelä-Pohjanmaa'), ('etela_savo', 'Etelä-Savo'), ('kainuu', 'Kainuu'), ('kanta_hame', 'Kanta-Häme'), ('keski_pohjanmaa', 'Keski-Pohjanmaa'), ('keski_suomi', 'Keski-Suomi'), ('kymenlaakso', 'Kymenlaakso'), ('lappi', 'Lappi'), ('pirkanmaa', 'Pirkanmaa'), ('pohjanmaa', 'Pohjanmaa'), ('pohjois_karjala', 'Pohjois-Karjala'), ('pohjois_pohjanmaa', 'Pohjois-Pohjanmaa'), ('pohjois_savo', 'Pohjois-Savo'), ('paijat_hame', 'Päijät-Häme'), ('satakunta', 'Satakunta'), ('uusimaa', 'Uusimaa'), ('varsinais_suomi', 'Varsinais-Suomi')], default='uusimaa', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'maakunnat',
            },
        ),
        migrations.CreateModel(
            name='Kunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(max_length=50)),
                ('maakunta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ohjelma.maakunta')),
            ],
            options={
                'verbose_name_plural': 'kunnat',
            },
        ),
        migrations.CreateModel(
            name='Työpiste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(max_length=50)),
                ('katuosoite', models.CharField(max_length=100)),
                ('postinumero', models.CharField(max_length=10)),
                ('postitoimipaikka', models.CharField(max_length=50)),
                ('kunta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ohjelma.kunta')),
            ],
            options={
                'verbose_name_plural': 'työpisteet',
            },
        ),
        migrations.CreateModel(
            name='Työntekijä',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etunimi', models.CharField(max_length=50)),
                ('sukunimi', models.CharField(max_length=50)),
                ('puhelin', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('katuosoite', models.CharField(max_length=100)),
                ('postinumero', models.CharField(max_length=10)),
                ('postitoimipaikka', models.CharField(max_length=50)),
                ('aloitus_pvm', models.DateField()),
                ('lopetus_pvm', models.DateField(blank=True, null=True)),
                ('työsuhteen_tyyppi', models.CharField(choices=[('vakituinen', 'Vakituinen'), ('määräaikainen', 'Määräaikainen')], default='vakituinen', max_length=50)),
                ('työkunta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ohjelma.kunta')),
                ('työmaakunta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ohjelma.maakunta')),
                ('työpiste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ohjelma.työpiste')),
            ],
            options={
                'verbose_name_plural': 'työntekijät',
            },
        ),
    ]
